import type { ReactNode } from "react";
import { Icon, type IconName } from "@/components/branding/Icon";
import { Logo } from "@/components/branding/Logo";
import { Button } from "@/components/ui/Button";
import { FaqSection } from "@/features/onboarding/components/FaqSection";

type LandingScreenProps = { isScrolled: boolean; onStart: () => void; onScrollTo: (id: string) => void };

const pillars: [IconName, string, string][] = [["brain", "Psicólogos especializados", "Acompañamiento profesional adaptado a tus necesidades."], ["book-open", "Psicoeducación", "Clases grupales para desarrollar herramientas psicológicas aplicables a la vida real."], ["message-circle", "IA emocional", "Acompañamiento disponible cuando lo necesites."], ["trending-up", "Seguimiento de progreso", "Visualizá tu evolución emocional y construí hábitos sostenibles."]];
const steps: [IconName, string, ReactNode][] = [["clipboard-list", "Completás tu evaluación inicial", <>Un breve <span className="font-semibold">cuestionario</span> para entender tus objetivos, necesidades y situación actual.</>], ["badge-check", "Elegís tu plan", <>Seleccioná la <span className="font-semibold">forma de acompañamiento</span> que mejor se adapta a tu momento y necesidades.</>], ["video", "Sesión de bienvenida sin costo", <>Una <span className="font-semibold">primera conversación</span> de aproximadamente 15 minutos para conocernos, definir objetivos y resolver dudas.</>], ["user-round-check", "Conocés a tu psicólogo", <>Te asignamos el profesional más <span className="font-semibold">adecuado</span> según tu perfil y objetivos.</>], ["heart-pulse", "Mental te acompaña", <>Sesiones, herramientas, <span className="font-semibold">seguimiento</span> e IA emocional para acompañarte todos los días.</>]];
const resources: [IconName, string][] = [["book-open", "Sesiones privadas online"], ["message-circle", "IA de apoyo emocional"], ["heart-pulse", "Registro de ánimo"], ["trending-up", "Seguimiento de progreso"], ["graduation-cap", "Recursos y clases"], ["badge-check", "Planes flexibles"]];

function Plan({ name, text, originalPrice, discountedPrice, features, featured, accessible, premium, onStart }: { name: string; text: string; originalPrice: string; discountedPrice: string; features: string[]; featured?: boolean; accessible?: boolean; premium?: boolean; onStart: () => void }) {
  return <article className={`plan${featured ? " featured" : ""}${premium ? " premium" : ""}`}>{accessible && <span className="tag">Más accesible</span>}{featured && <span className="tag">Más elegido</span>}<h3>{name}</h3><p>{text}</p><span className="prelaunch-discount-badge">30% OFF pre-lanzamiento</span><div className="prelaunch-price"><span className="original-price">{originalPrice} <small>UYU / mes</small></span><b>{discountedPrice} <small>UYU / mes</small></b></div><p className="prelaunch-price-note">Anotate ahora y accedé a este beneficio cuando lancemos.</p><hr /><ul>{features.map((item) => <li key={item}>{item}</li>)}</ul><Button variant="primary" onClick={onStart}>{name === "Plan Básico" ? "Elegir Básico →" : name === "Plan Full" ? "Elegir Full →" : "Elegir Premium →"}</Button><div className="certificate">{name === "Plan Básico" ? "Los certificados reflejan formación continua. No reemplazan títulos universitarios ni certificaciones habilitantes." : name === "Plan Full" ? "Sumás sesiones privadas para profundizar tu proceso junto a un profesional." : "Incluye un acompañamiento profesional sostenido, según la frecuencia elegida."}</div></article>;
}

export function LandingScreen({ isScrolled, onStart, onScrollTo }: LandingScreenProps) {
  return <><header className={`nav${isScrolled ? " nav-scrolled" : ""}`}><Logo /><nav><button onClick={() => onScrollTo("que-es-mental")}>¿Qué es Mental?</button><button onClick={() => onScrollTo("como-funciona")}>¿Cómo funciona?</button><button onClick={onScrollTo.bind(null, "planes")}>Planes</button></nav><Button className="nav-cta" onClick={onStart}>Sumarme a la lista →</Button></header>
    <main className="hero"><section><div className="eyebrow">UN ESPACIO SEGURO PARA CUIDARTE, A TU RITMO.</div><h1><span className="headline-first-line"><i>Terapia online</i> con</span><br />acompañamiento<br />más allá de<br />la sesión.</h1><p>Mental conecta personas con psicólogos y les da herramientas diarias para registrar cómo se sienten, ordenar sus emociones y llegar mejor a cada sesión.</p><div className="actions"><Button onClick={onStart}>Empezar ahora →</Button><Button variant="outline" onClick={() => onScrollTo("planes")}>Ver planes</Button></div></section><aside className="human-hero"><img className="therapy-photo" src="/assets/hero-therapy.png" alt="Mujer en una sesión psicológica online desde su casa" /><div className="float f1"><Icon name="calendar-clock" /><b>Próxima sesión</b><small>Mañana · 18:30</small></div><div className="float f2"><Icon name="book-open" /><b>Nueva clase disponible</b><small>Manejo de la ansiedad</small></div><div className="float f3"><Icon name="award" /><b>Certificado obtenido</b><small>Comunicación efectiva</small></div><div className="float f4"><Icon name="message-circle" /><b>Mental IA disponible</b><small>¿Cómo te sentís hoy?</small></div><div className="hero-price">Terapia desde <strong>$990</strong> por sesión.</div></aside></main>
    <section id="que-es-mental" className="what what-expanded"><div className="what-copy"><div className="kicker">¿QUÉ ES MENTAL?</div><h2>Mucho más que<br />terapia online.</h2><p>Mental combina psicólogos, educación emocional e inteligencia artificial para ayudarte a desarrollar herramientas que mejoren tu bienestar, tus relaciones y tu crecimiento personal.</p><p>Creemos que la salud mental no debería limitarse a una sesión por semana.</p><p>Por eso creamos un espacio donde podés acceder a acompañamiento profesional, clases de psicoeducación, seguimiento emocional y recursos diseñados para ayudarte a sentirte mejor, afrontar los desafíos del día a día y potenciar tu desarrollo personal.</p><Button onClick={() => onScrollTo("como-funciona")}>Conocer cómo funciona →</Button></div><div className="pillars">{pillars.map(([icon, title, text]) => <article key={title}><Icon name={icon} /><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
    <section id="como-funciona" className="how"><div className="how-head"><div><div className="kicker">ASÍ DE SIMPLE</div><h2>Tu espacio para sentirte<br />acompañada/o, todos los días.</h2></div><p>Desde el primer contacto hasta el acompañamiento diario, diseñamos una experiencia simple, humana y profesional.</p></div><div className="journey">{steps.map(([icon, title, text], index) => <article className="step" key={title}><div className="visual"><Icon name={icon} /></div><div><strong>0{index + 1}</strong><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
    <section id="recursos" className="resources"><div><div className="kicker">TODO EN UN MISMO LUGAR</div><h2>El cuidado no tiene por qué esperar a la próxima sesión.</h2><p>Clases, ejercicios, IA emocional y herramientas simples para que tu bienestar tenga un lugar en todos los días.</p><Button onClick={() => onScrollTo("planes")}>Conocé Mental →</Button></div><div className="resource-grid">{resources.map(([icon, text]) => <div className="resource" key={text}><Icon name={icon} />{text}</div>)}</div></section>
    <section id="planes" className="plans"><div className="kicker">PLANES MENTAL</div><h2>Elegí el plan que mejor acompaña tu proceso</h2><p>Anotate al pre-lanzamiento y reservá un 30% OFF para cuando Mental esté disponible.</p><div className="plan-grid"><Plan name="Plan Básico" text="Herramientas psicológicas prácticas para tu bienestar." originalPrice="desde $390" discountedPrice="desde $273" accessible onStart={onStart} features={["Lecturas diarias de psicoeducación", "Seminarios en vivo por Zoom", "Certificados de asistencia", "Registro emocional diario", "IA de apoyo emocional", "Ejercicios guiados", "25% OFF en sesiones terapéuticas"]} /><Plan name="Plan Full" text="Psicoeducación y un seguimiento profesional más cercano." originalPrice="desde $2390" discountedPrice="desde $1673" featured onStart={onStart} features={["Todo lo del Plan Básico", "2 sesiones mensuales con tu psicólogo", "Recomendaciones y ejercicios adaptados a tu proceso terapéutico"]} /><Plan name="Plan Premium" text="Para comprometerte con tu proceso al máximo" originalPrice="desde $3990" discountedPrice="desde $2793" premium onStart={onStart} features={["Todo lo del Plan Básico", "4 sesiones mensuales con psicólogo", "Recomendaciones y ejercicios adaptados a tu proceso terapéutico"]} /></div></section>
    <FaqSection />
    <section className="cta"><div><div className="eyebrow">PRE-LANZAMIENTO MENTAL</div><h2>Sumate a la lista de espera y reservá tu 30% OFF.</h2><Button onClick={onStart}>Sumarme a la lista →</Button></div><Icon name="message-circle" /></section><footer className="footer"><div className="footer-brand"><Logo /><p>Acompañamiento emocional profesional, accesible y a tu ritmo.</p></div><div><h3>¿Querés saber más?</h3><a href="mailto:hola@mental.uy">Hablar con asesoramiento</a><a href="mailto:hola@mental.uy?subject=Consulta%20sobre%20Mental">Cómo funciona Mental</a><a href="/terminos-y-condiciones">Términos y condiciones</a></div><div><h3>Para profesionales</h3><a href="/postulacion-psicologos">Postularme como psicólogo/a</a><a href="/postulacion-psicologos">Sumarme a la red Mental</a></div><div><h3>Contacto</h3><a href="mailto:hola@mental.uy">hola@mental.uy</a><a href="#planes" onClick={(event) => { event.preventDefault(); onScrollTo("planes"); }}>Ver planes</a></div><div className="footer-bottom">© 2026 Mental · Un espacio para cuidarte con más compañía.</div></footer></>;
}
