import { Icon } from "@/components/branding/Icon";
import { Button } from "@/components/ui/Button";
import { DashboardCard } from "@/components/layout/DashboardCard";
import type { UserProfile } from "@/types/profile";

export function ProfileScreen({ profile, onLogout, onPlan }: { profile: UserProfile | null; onLogout: () => void; onPlan: () => void }) {
  const firstName = profile?.firstName || "Sin completar";
  const lastName = profile?.lastName || "Sin completar";
  const email = profile?.email || "Sin completar";
  const fullName = [profile?.firstName, profile?.lastName].filter(Boolean).join(" ");
  const name = fullName || (profile?.email ? profile.email.split("@")[0] : "Tu cuenta");
  const avatarInitials = fullName ? fullName.split(" ").map((word) => word[0]).join("").slice(0, 2) : (profile?.email?.charAt(0).toUpperCase() || "M");
  return <><div className="view-head"><div><h1>Tu perfil</h1><p>Tu información, plan y configuraciones en un solo lugar.</p></div></div><section className="profile-overview">{profile?.avatarUrl ? <img className="profile-avatar-image" src={profile.avatarUrl} alt={`Foto de perfil de ${name}`} /> : <span>{avatarInitials}</span>}<div><small>MI CUENTA</small><h2>{name}</h2><p>{email}</p></div></section><section className="profile-layout"><DashboardCard className="profile-section"><div className="profile-section-head"><Icon name="user-circle" /><div><h2>Datos personales</h2><p>La información principal de tu cuenta.</p></div></div><div className="profile-data-row"><span>Nombre</span><b>{firstName}</b></div><div className="profile-data-row"><span>Apellido</span><b>{lastName}</b></div><div className="profile-data-row"><span>Email</span><b>{email}</b></div><div className="profile-data-row"><span>Edad</span><b>{profile?.age ?? "Sin completar"}</b></div><div className="profile-data-row"><span>Celular</span><b>{profile?.phone ?? "Sin completar"}</b></div><div className="profile-data-row"><span>Dirección</span><b>{profile?.address ?? "Sin completar"}</b></div></DashboardCard><DashboardCard className="profile-section"><div className="profile-section-head"><Icon name="sparkles" /><div><h2>Plan y acceso</h2><p>Tu acompañamiento actual.</p></div></div><div className="profile-data-row"><span>Plan actual</span><b>Plan Básico</b></div><div className="profile-data-row"><span>Estado</span><b>Prueba gratuita · Día 1 de 7</b></div><Button onClick={onPlan}>Ver mi plan</Button></DashboardCard></section><DashboardCard className="account-settings"><div className="profile-section-head"><Icon name="bell" /><div><h2>Configuración de cuenta</h2><p>Preferencias y documentación de Mental.</p></div></div><div className="account-settings-links"><a href="#terminos-y-privacidad">Términos y condiciones <span>→</span></a><a id="terminos-y-privacidad" href="#terminos-y-privacidad">Privacidad y uso de datos <span>→</span></a></div></DashboardCard><section className="security-zone"><div><small>ZONA DE SEGURIDAD</small><h2>Configuración avanzada</h2><p>Acciones relacionadas con el acceso y la seguridad de tu cuenta.</p></div><div className="security-links"><button type="button">Cambiar contraseña</button><button type="button" onClick={onLogout}>Cerrar sesión</button><details><summary>Eliminar cuenta</summary><p>Esta acción requiere confirmación adicional. Por ahora no se realizará ningún borrado.</p><button type="button" disabled>Confirmar eliminación</button></details></div></section></>;
}
