export type Question = { title: string; desc: string; type?: "name" | "input"; inputType?: "number"; placeholder?: string; list?: string[]; options?: string[]; multi?: boolean; other?: string };

export const questions: Question[] = [
  { title: "Antes de empezar, ¿cómo te llamás?", desc: "Queremos acompañarte de una manera más personal desde el primer momento.", type: "name" },
  { title: "Para empezar, ¿cuántos años tenés?", desc: "Es un dato simple que nos ayuda a recomendarte una experiencia más cercana a vos.", type: "input", inputType: "number", placeholder: "Ingresá tu edad" },
  { title: "¿En qué país vivís?", desc: "Así podemos tener en cuenta tu contexto y la disponibilidad de profesionales.", type: "input", placeholder: "Seleccioná tu país", list: ["Uruguay", "Argentina", "Chile", "México", "Colombia", "Perú", "Otro país"] },
  { title: "¿En qué ciudad vivís?", desc: "Esto nos ayuda a entender mejor tu contexto cotidiano.", type: "input", placeholder: "¿En qué ciudad vivís?" },
  { title: "¿Cómo te identificás?", desc: "Queremos que tu experiencia se sienta cómoda, segura y respetuosa.", options: ["Mujer", "Hombre", "No binario", "Género fluido", "Agénero", "Prefiero describirme", "Prefiero no responder"], other: "Prefiero describirme", placeholder: "Contanos cómo te identificás" },
  { title: "¿Querés contarnos tu orientación sexual?", desc: "Esta pregunta es opcional y sólo busca cuidar la afinidad de tu experiencia.", options: ["Heterosexual", "Homosexual", "Bisexual", "Pansexual", "Demisexual", "Asexual", "Queer", "Prefiero describirme", "Prefiero no responder"], other: "Prefiero describirme", placeholder: "Contanos cómo te identificás" },
  { title: "¿Cuál describe mejor tu situación actual?", desc: "No hay respuestas correctas; sólo queremos entender un poco más tu momento.", options: ["Soltera/o", "En pareja", "Casada/o o conviviendo", "Separada/o", "Prefiero no decirlo"] },
  { title: "¿Has hecho terapia anteriormente?", desc: "Podemos acompañarte tanto si ya conocés este camino como si estás por dar tu primer paso.", options: ["Sí, actualmente", "Sí, en el pasado", "No, sería mi primera vez"] },
  { title: "¿Cómo te sentís en este momento?", desc: "Elegí la opción que mejor refleje cómo venís últimamente.", options: ["Con mucha energía", "En calma", "Con algunas preocupaciones", "Estresada/o o ansiosa/o", "Con el ánimo bajo"] },
  { title: "¿Qué te gustaría trabajar hoy?", desc: "Podés elegir todas las que se sientan importantes para vos.", options: ["Ansiedad y estrés", "Autoestima", "Relaciones", "Comunicación", "Gestión emocional", "Crecimiento personal", "Otro"], multi: true, other: "Otro", placeholder: "Contanos qué te gustaría trabajar" },
  { title: "¿Qué tan importante es para vos desarrollar comunicación, inteligencia emocional y manejo del estrés?", desc: "Donde 1 es poco importante y 5 muy importante.", options: ["1", "2", "3", "4", "5"] },
  { title: "¿Cómo están tus relaciones hoy?", desc: "Pensá en vínculos de pareja, familia, amistades o trabajo.", options: ["Me siento acompañada/o", "Hay cosas que me gustaría mejorar", "Me generan bastante preocupación", "Prefiero no responder"] },
  { title: "¿Qué lugar ocupa el estrés en tu día a día?", desc: "Buscamos herramientas que puedan servirte en tu vida real.", options: ["Poco", "Aparece de vez en cuando", "Está bastante presente", "Siento que me sobrepasa"] },
  { title: "¿Qué tipo de experiencia te interesa más?", desc: "Mental puede acompañarte de distintas maneras.", options: ["Aprender herramientas psicológicas", "Hablar con un profesional", "Combinar ambas cosas"] },
  { title: "¿Tenés alguna preferencia sobre tu profesional?", desc: "Si podemos tenerla en cuenta, lo haremos.", options: ["Prefiero mujer", "Prefiero hombre", "No tengo preferencia"] },
  { title: "¿Qué estilo de acompañamiento te resulta más cómodo?", desc: "Esto nos ayuda a buscar una afinidad más natural.", options: ["Cálido y cercano", "Práctico y con herramientas", "Reflexivo y profundo", "Una combinación"] },
  { title: "¿Cuál es tu principal objetivo hoy?", desc: "Elegí lo que hoy se sienta como un buen punto de partida.", options: ["Sentirme más en calma", "Comprender mejor mis emociones", "Mejorar mis vínculos", "Crear hábitos de bienestar", "Crecer personalmente", "Otro"], other: "Otro", placeholder: "Contanos cuál es tu objetivo" },
];
