import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { ScreenLayout } from "@/components/layout/ScreenLayout";

type Form = { firstName: string; lastName: string; email: string; password: string; confirm: string };
type RegisterScreenProps = { form: Form; error: string | null; isPending: boolean; onChange: (field: keyof Form, value: string) => void; onSubmit: () => void; onClose: () => void };
export function RegisterScreen({ form, error, isPending, onChange, onSubmit, onClose }: RegisterScreenProps) {
  return <ScreenLayout progress={100} onClose={onClose}><section className="flow-step"><div className="overline">CREÁ TU ESPACIO</div><h1>Estás a un paso de empezar.</h1><p>Guardá tu experiencia y accedé a tu espacio personal.</p><form className="register-form" onSubmit={(event) => { event.preventDefault(); onSubmit(); }}><label>Nombre<Input required value={form.firstName} onChange={(event) => onChange("firstName", event.target.value)} placeholder="Tu nombre" /></label><label>Apellido<Input required value={form.lastName} onChange={(event) => onChange("lastName", event.target.value)} placeholder="Tu apellido" /></label><label>Email<Input required type="email" value={form.email} onChange={(event) => onChange("email", event.target.value)} placeholder="nombre@email.com" /></label><label>Contraseña<Input required type="password" minLength={8} value={form.password} onChange={(event) => onChange("password", event.target.value)} placeholder="Mínimo 8 caracteres" /></label><label className="span-full">Repetir contraseña<Input required type="password" minLength={8} value={form.confirm} onChange={(event) => onChange("confirm", event.target.value)} placeholder="Repetí tu contraseña" /></label><p className="flow-error span-full" role="alert">{error}</p><Button className="span-full" disabled={isPending} type="submit">{isPending ? "Creando tu cuenta..." : "Crear mi cuenta →"}</Button></form></section></ScreenLayout>;
}
