import { Icon } from "@/components/branding/Icon";
import { Button } from "@/components/ui/Button";
import { DashboardCard } from "@/components/layout/DashboardCard";
import type { Seminar } from "@/types/seminar";

export function SeminarsScreen({ seminars, reservedId, pending, onReserve, onCancel }: { seminars: Seminar[]; reservedId: string | null; pending: boolean; onReserve: (id: string) => void; onCancel: (id: string) => void }) {
  const seminar = seminars[0];
  if (!seminar) return null;
  const reserved = seminar.id === reservedId;
  return <><div className="view-head"><div><h1>Próximo seminario</h1><p>Un encuentro en vivo para sumar herramientas a tu semana.</p></div></div><section className={`recommended-seminar${reserved ? " seminar-is-reserved" : ""}`}><div className="seminar-feature-head"><span><Icon name="presentation" /></span><div><small>ENCUENTRO RECOMENDADO</small><h2>{seminar.title}</h2><div className="seminar-meta"><strong>Martes 16 de julio · 19:00 hs</strong><span>Encuentro online por Zoom</span></div></div><span className="seminar-capacity">{seminar.capacity} cupos disponibles</span></div><div className="seminar-detail-grid seminar-detail-grid-single"><div><small>LO DICTA</small><div className="seminar-professional"><img src="/assets/hero-therapy.png" alt="Lic. Lucía Pereira" /><div><h3>Lic. Lucía Pereira</h3><p>Psicóloga clínica · Especialista en ansiedad y regulación emocional.</p></div></div></div><div className="seminar-main-topic"><small>EN ESTE ENCUENTRO</small><p>Vamos a trabajar sobre cómo identificar señales tempranas de estrés, reconocer patrones de pensamiento que aumentan la ansiedad y aplicar herramientas simples para regularte durante el día. También veremos cómo construir pequeños hábitos de autocuidado que puedan sostenerse en la rutina, sin que se sientan como una obligación más.</p></div></div><div className="seminar-feature-actions"><div>{reserved ? <div className="seminar-reserved-box"><span className="seminar-reserved"><Icon name="badge-check" /> Lugar reservado</span><p>Te guardamos un lugar para este seminario. Vas a recibir el acceso y recordatorios antes del encuentro.</p></div> : <small>Durante la prueba gratuita podés asistir sin certificado.</small>}</div>{reserved ? <button className="seminar-cancel-button" type="button" onClick={() => onCancel(seminar.id)}>Cancelar asistencia</button> : <Button disabled={pending} onClick={() => onReserve(seminar.id)}>{pending ? "Reservando..." : "Reservar lugar"}</Button>}</div></section><DashboardCard className="seminar-material"><div><span><Icon name="book-open" /></span><div><small>MATERIAL DEL SEMINARIO</small><h3>Guía de acompañamiento</h3><p>El material se habilita automáticamente 2 horas antes del encuentro.</p></div></div><Button variant="outline" disabled>Disponible 2 horas antes</Button></DashboardCard></>;
}
